# Generated by Django 4.2.4 on 2023-09-12 11:19

from django.db import migrations, models
import textExtract.models


class Migration(migrations.Migration):

    dependencies = [
        ('textExtract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='image',
            field=models.ImageField(upload_to=textExtract.models.upload_location),
        ),
    ]
