# Generated by Django 4.2.4 on 2023-10-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textExtract', '0002_alter_carddata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='carddata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='carddata',
            name='number',
        ),
        migrations.AlterField(
            model_name='carddata',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
